---
- name: Install Docker and Docker Compose
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started 